Updated publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -59,8 +59,9 @@ jobs:
 
       - name: Create Pull Request
         run: |
-          PR_TITLE="Release ${GITHUB_REF#refs/tags/v}"
-          PR_BODY="This PR updates the version to ${GITHUB_REF#refs/tags/v}"
+          PR_TITLE="Release $(echo ${GITHUB_REF#refs/tags/v})"
+          PR_BODY="This PR updates the version to $(echo ${GITHUB_REF#refs/tags/v})"
+          echo "Creating Pull Request with title: $PR_TITLE and body: $PR_BODY"
           gh pr create --base main --head $NEW_BRANCH --title "$PR_TITLE" --body "$PR_BODY"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -73,19 +74,24 @@ jobs:
       - name: Wait for PR to be created
         run: |
           for i in {1..10}; do
-            PR_NUMBER=$(gh pr list --state open --head "$NEW_BRANCH" --json "number" --jq '.[0].number')
+            PR_NUMBER=$(gh pr list --state open --head "$NEW_BRANCH" --json number --jq '.[0].number')
             if [ -n "$PR_NUMBER" ]; then
               break
             fi
             echo "Pull request not found, retrying in 10 seconds..."
             sleep 10
           done
+          if [ -z "$PR_NUMBER" ]; then
+            echo "Error: Pull request not found"
+            exit 1
+          fi
+          echo "Pull request found: $PR_NUMBER"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Merge Pull Request
         run: |
-          PR_NUMBER=$(gh pr list --state open --head "$NEW_BRANCH" --json "number" --jq '.[0].number')
+          PR_NUMBER=$(gh pr list --state open --head "$NEW_BRANCH" --json number --jq '.[0].number')
           echo "Merging PR #${PR_NUMBER}"
           gh pr merge "$PR_NUMBER" --squash
         env:
